/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module fsm(clk_i, reset_i, data_i, match_o);
  wire _0_;
  input clk_i;
  wire curr_state;
  input data_i;
  output match_o;
  wire next_state;
  input reset_i;
  MUX2_X1 _1_ (
    .A(curr_state),
    .B(_0_),
    .S(data_i),
    .Z(next_state)
  );
  AND2_X1 _2_ (
    .A1(data_i),
    .A2(curr_state),
    .ZN(match_o)
  );
  DFFR_X1 _3_ (
    .CK(clk_i),
    .D(next_state),
    .Q(curr_state),
    .QN(_0_),
    .RN(reset_i)
  );
endmodule
