/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module fsm(clk_i, reset_i, data_i, match_o);
  wire _0_;
  wire _1_;
  input clk_i;
  wire curr_state;
  input data_i;
  output match_o;
  input reset_i;
  INV_X1 _2_ (
    .A(curr_state),
    .ZN(_0_)
  );
  NOR2_X1 _3_ (
    .A1(data_i),
    .A2(_0_),
    .ZN(match_o)
  );
  DFFR_X1 _4_ (
    .CK(clk_i),
    .D(data_i),
    .Q(curr_state),
    .QN(_1_),
    .RN(reset_i)
  );
endmodule
